language: ruby
before_script:
  - mysql -e 'CREATE DATABASE sns;' # funny how inconsistent that works
  - mysql -e "CREATE USER 'sns'@'localhost' IDENTIFIED BY 'sns';" -u root
  - mysql -e "GRANT ALL ON sns.* TO 'sns'@'localhost';" -u root
  - psql -c "CREATE ROLE sns LOGIN PASSWORD 'sns' NOSUPERUSER INHERIT CREATEDB NOCREATEROLE;" -U postgres
  - psql -c "CREATE DATABASE sns WITH OWNER = sns;" -U postgres
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - rbx-18mode
  - rbx-19mode
env:
  - DATABASE=sqlite3
  - DATABASE=postgresql
  - DATABASE=mysql
